version: "3.7"
services:
  proxy:
    image: nginx:1.15.2-alpine
    ports:
      - "80:80"

    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf

      - ./client/dist:/app/www/
      - ./client/index.html:/app/www/index.html

    networks:
      - frontend

    depends_on:
      - server

  client:
    env_file: .env
    build:
      context: ./client
      target: build
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    volumes:
      - ./client:/app
      - client_modules:/app/node_modules
    networks:
      - frontend

  server:
    env_file: .env
    build:
      context: ./server
      target: build

    volumes:
      - ./server:/app
      - server_modules:/app/node_modules

    networks:
      - backend
      - frontend

    depends_on:
      - database

  database:
    env_file: .env
    image: postgres:10-alpine
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  database:
  client_modules:
  server_modules:
