const { assign } = require( 'lodash' );

exports.seed = async knex => {
  // Deletes ALL existing entries
    await knex('task_order').del();
    
    const mous = await knex( 'mou' ).select( [ 'id' ] );

    const taskOrders = [{
        "mou_id": "mou_id",
        "budget": 14000,
        "overhead_rate": 0.237,
        "task_name": "Daltfresh",
        "contact_name": "Traver Cathee",
        "contact_phone": "143-210-1132",
        "project_manager": "Everett Cressey",
        "task_description": "sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo",
        "start_date": "10/22/2017",
        "end_date": "12/18/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 97629,
        "overhead_rate": 0.84,
        "task_name": "Regrant",
        "contact_name": "Karney Bleasdille",
        "contact_phone": "212-431-5818",
        "project_manager": "Skipton Stienton",
        "task_description": "hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum",
        "start_date": "12/23/2017",
        "end_date": "12/24/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 169745,
        "overhead_rate": 0.569,
        "task_name": "Solarbreeze",
        "contact_name": "Mallory Leven",
        "contact_phone": "867-517-2248",
        "project_manager": "Cayla De la croix",
        "task_description": "nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo",
        "start_date": "04/16/2018",
        "end_date": "04/29/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 198292,
        "overhead_rate": 0.143,
        "task_name": "Opela",
        "contact_name": "Carina Sporner",
        "contact_phone": "108-427-3087",
        "project_manager": "Glennie Nare",
        "task_description": "congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero",
        "start_date": "05/04/2018",
        "end_date": "02/18/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 91512,
        "overhead_rate": 0.17,
        "task_name": "Veribet",
        "contact_name": "Kerstin Mussettini",
        "contact_phone": "331-983-2965",
        "project_manager": "Lay Grimditch",
        "task_description": "erat quisque erat eros viverra eget congue eget semper rutrum nulla",
        "start_date": "01/09/2018",
        "end_date": "02/14/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 189531,
        "overhead_rate": 0.023,
        "task_name": "Daltfresh",
        "contact_name": "Agathe Kondratowicz",
        "contact_phone": "840-338-7022",
        "project_manager": "Jacquette Laban",
        "task_description": "luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus",
        "start_date": "09/06/2018",
        "end_date": "06/09/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 31502,
        "overhead_rate": 0.13,
        "task_name": "Voyatouch",
        "contact_name": "Erv MacKimmie",
        "contact_phone": "843-325-8472",
        "project_manager": "Marius Aries",
        "task_description": "orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo",
        "start_date": "06/19/2018",
        "end_date": "08/02/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 80934,
        "overhead_rate": 0.027,
        "task_name": "Stringtough",
        "contact_name": "Cammy Fouracres",
        "contact_phone": "204-984-0762",
        "project_manager": "Codi Burley",
        "task_description": "viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est",
        "start_date": "10/24/2017",
        "end_date": "11/05/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 15169,
        "overhead_rate": 0.027,
        "task_name": "Andalax",
        "contact_name": "Charlie Aizic",
        "contact_phone": "154-304-8909",
        "project_manager": "Nevin Gilbanks",
        "task_description": "vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque",
        "start_date": "09/17/2018",
        "end_date": "09/23/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 102793,
        "overhead_rate": 0.971,
        "task_name": "Bigtax",
        "contact_name": "Darbee Yea",
        "contact_phone": "852-217-6542",
        "project_manager": "Berkley Kalinovich",
        "task_description": "sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut",
        "start_date": "04/24/2018",
        "end_date": "02/19/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 91440,
        "overhead_rate": 0.612,
        "task_name": "Andalax",
        "contact_name": "Flint Gadd",
        "contact_phone": "876-396-2926",
        "project_manager": "Haleigh Lindenboim",
        "task_description": "fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat",
        "start_date": "09/01/2018",
        "end_date": "09/02/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 15844,
        "overhead_rate": 0.622,
        "task_name": "Daltfresh",
        "contact_name": "Max Shiril",
        "contact_phone": "243-822-0192",
        "project_manager": "Liv Oldknowe",
        "task_description": "congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat",
        "start_date": "04/05/2018",
        "end_date": "03/07/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 174449,
        "overhead_rate": 0.483,
        "task_name": "Veribet",
        "contact_name": "Kathie Dahlborg",
        "contact_phone": "825-995-3249",
        "project_manager": "Freddie Stoneman",
        "task_description": "curabitur gravida nisi at nibh in hac habitasse platea dictumst",
        "start_date": "10/25/2017",
        "end_date": "06/30/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 72819,
        "overhead_rate": 0.485,
        "task_name": "Tampflex",
        "contact_name": "Melvin Aizikowitz",
        "contact_phone": "830-500-9298",
        "project_manager": "Alecia Errowe",
        "task_description": "augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean",
        "start_date": "10/29/2017",
        "end_date": "09/17/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 53116,
        "overhead_rate": 0.086,
        "task_name": "Voltsillam",
        "contact_name": "Adria Worlidge",
        "contact_phone": "266-894-7434",
        "project_manager": "Jeniece Haily",
        "task_description": "lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue",
        "start_date": "03/01/2018",
        "end_date": "03/18/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 85467,
        "overhead_rate": 0.883,
        "task_name": "Fixflex",
        "contact_name": "Jenny Bradwell",
        "contact_phone": "573-181-0687",
        "project_manager": "Erda Di Maggio",
        "task_description": "dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut",
        "start_date": "02/08/2018",
        "end_date": "10/26/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 115598,
        "overhead_rate": 0.996,
        "task_name": "Tresom",
        "contact_name": "Terrie Wyldes",
        "contact_phone": "336-967-4135",
        "project_manager": "Vanessa Charlet",
        "task_description": "eu felis fusce posuere felis sed lacus morbi sem mauris",
        "start_date": "12/17/2017",
        "end_date": "09/26/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 43617,
        "overhead_rate": 0.605,
        "task_name": "Stringtough",
        "contact_name": "Pauli Moynihan",
        "contact_phone": "411-931-4136",
        "project_manager": "Nariko Overbury",
        "task_description": "cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",
        "start_date": "10/27/2017",
        "end_date": "07/31/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 134007,
        "overhead_rate": 0.844,
        "task_name": "Latlux",
        "contact_name": "Packston Frood",
        "contact_phone": "154-606-5137",
        "project_manager": "Una Yushachkov",
        "task_description": "commodo placerat praesent blandit nam nulla integer pede justo lacinia eget",
        "start_date": "10/24/2017",
        "end_date": "01/09/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 61601,
        "overhead_rate": 0.942,
        "task_name": "Home Ing",
        "contact_name": "Vyky Forte",
        "contact_phone": "776-985-5336",
        "project_manager": "Maitilde Figure",
        "task_description": "convallis morbi odio odio elementum eu interdum eu tincidunt in",
        "start_date": "10/16/2017",
        "end_date": "07/15/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 54208,
        "overhead_rate": 0.308,
        "task_name": "Trippledex",
        "contact_name": "Harmony Cleere",
        "contact_phone": "425-139-6191",
        "project_manager": "Ole Hebblethwaite",
        "task_description": "congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus",
        "start_date": "11/11/2017",
        "end_date": "10/31/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 73963,
        "overhead_rate": 0.05,
        "task_name": "Flowdesk",
        "contact_name": "Max Twiddle",
        "contact_phone": "851-408-6101",
        "project_manager": "Bogart Deeprose",
        "task_description": "quisque porta volutpat erat quisque erat eros viverra eget congue eget",
        "start_date": "09/28/2017",
        "end_date": "06/15/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 25583,
        "overhead_rate": 0.506,
        "task_name": "Regrant",
        "contact_name": "Marijn Doulden",
        "contact_phone": "303-954-5216",
        "project_manager": "Star Hinstock",
        "task_description": "aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum",
        "start_date": "11/12/2017",
        "end_date": "03/06/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 112106,
        "overhead_rate": 0.694,
        "task_name": "Zaam-Dox",
        "contact_name": "Patrica Aronow",
        "contact_phone": "244-968-2185",
        "project_manager": "Gnni Pesek",
        "task_description": "aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque",
        "start_date": "07/07/2018",
        "end_date": "04/16/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 99310,
        "overhead_rate": 0.281,
        "task_name": "Fixflex",
        "contact_name": "Bobbie Harbottle",
        "contact_phone": "474-134-4338",
        "project_manager": "Lotte Vany",
        "task_description": "elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien",
        "start_date": "06/08/2018",
        "end_date": "06/25/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 182051,
        "overhead_rate": 0.699,
        "task_name": "Tresom",
        "contact_name": "Mariellen Backe",
        "contact_phone": "594-652-2377",
        "project_manager": "Gayelord Forcade",
        "task_description": "mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis",
        "start_date": "06/23/2018",
        "end_date": "04/06/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 19824,
        "overhead_rate": 0.7,
        "task_name": "Alphazap",
        "contact_name": "Kiah Koppen",
        "contact_phone": "628-136-3509",
        "project_manager": "Jessie Clelland",
        "task_description": "lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat",
        "start_date": "10/27/2017",
        "end_date": "03/17/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 197219,
        "overhead_rate": 0.148,
        "task_name": "Bitwolf",
        "contact_name": "Terry Harradence",
        "contact_phone": "359-552-1434",
        "project_manager": "Daisy Guildford",
        "task_description": "lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a",
        "start_date": "09/16/2018",
        "end_date": "05/18/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 184059,
        "overhead_rate": 0.469,
        "task_name": "Y-find",
        "contact_name": "Madelaine Savell",
        "contact_phone": "623-917-4692",
        "project_manager": "Hailey Clissold",
        "task_description": "ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique",
        "start_date": "05/09/2018",
        "end_date": "07/24/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 45609,
        "overhead_rate": 0.604,
        "task_name": "Overhold",
        "contact_name": "Andrei Tailby",
        "contact_phone": "282-165-1187",
        "project_manager": "Roth Capin",
        "task_description": "suscipit a feugiat et eros vestibulum ac est lacinia nisi",
        "start_date": "11/03/2017",
        "end_date": "01/01/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 72776,
        "overhead_rate": 0.474,
        "task_name": "Regrant",
        "contact_name": "Calida Broggelli",
        "contact_phone": "668-464-9111",
        "project_manager": "Eliot Hambribe",
        "task_description": "posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante",
        "start_date": "03/18/2018",
        "end_date": "05/08/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 103084,
        "overhead_rate": 0.587,
        "task_name": "Sub-Ex",
        "contact_name": "Randa Crate",
        "contact_phone": "843-107-2014",
        "project_manager": "Letti Tansill",
        "task_description": "cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam",
        "start_date": "02/05/2018",
        "end_date": "01/05/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 66111,
        "overhead_rate": 0.464,
        "task_name": "Temp",
        "contact_name": "Stormie Alderman",
        "contact_phone": "466-867-1599",
        "project_manager": "Bambi Langdale",
        "task_description": "sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla",
        "start_date": "03/15/2018",
        "end_date": "05/21/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 56642,
        "overhead_rate": 0.905,
        "task_name": "Bigtax",
        "contact_name": "Gaspar Schoroder",
        "contact_phone": "982-424-2830",
        "project_manager": "Debera Lamplugh",
        "task_description": "commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet",
        "start_date": "03/23/2018",
        "end_date": "12/01/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 107700,
        "overhead_rate": 0.1,
        "task_name": "Cardify",
        "contact_name": "Karin Bartolacci",
        "contact_phone": "360-697-1188",
        "project_manager": "Deerdre Hellen",
        "task_description": "sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec",
        "start_date": "03/11/2018",
        "end_date": "10/15/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 30338,
        "overhead_rate": 0.103,
        "task_name": "Ventosanzap",
        "contact_name": "Rusty Kaszper",
        "contact_phone": "879-372-5047",
        "project_manager": "Kermit Norwell",
        "task_description": "magna at nunc commodo placerat praesent blandit nam nulla integer",
        "start_date": "02/21/2018",
        "end_date": "08/04/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 189179,
        "overhead_rate": 0.336,
        "task_name": "Tres-Zap",
        "contact_name": "Gretchen Pina",
        "contact_phone": "542-325-7480",
        "project_manager": "Caria Karpeev",
        "task_description": "sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec",
        "start_date": "06/21/2018",
        "end_date": "12/28/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 28036,
        "overhead_rate": 0.145,
        "task_name": "Wrapsafe",
        "contact_name": "Bren Cotter",
        "contact_phone": "322-764-5527",
        "project_manager": "Cordelie Kennet",
        "task_description": "faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend",
        "start_date": "03/27/2018",
        "end_date": "07/26/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 69426,
        "overhead_rate": 0.422,
        "task_name": "Domainer",
        "contact_name": "Mata Pringuer",
        "contact_phone": "375-128-9272",
        "project_manager": "Linoel Navarro",
        "task_description": "purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus",
        "start_date": "01/16/2018",
        "end_date": "10/30/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 105915,
        "overhead_rate": 0.928,
        "task_name": "Temp",
        "contact_name": "Jarrid Byart",
        "contact_phone": "651-428-4587",
        "project_manager": "Kylynn Willingam",
        "task_description": "et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna",
        "start_date": "05/24/2018",
        "end_date": "05/03/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 64275,
        "overhead_rate": 0.842,
        "task_name": "Flowdesk",
        "contact_name": "Ruy Plaster",
        "contact_phone": "173-463-4738",
        "project_manager": "Dell Slimm",
        "task_description": "sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique",
        "start_date": "12/14/2017",
        "end_date": "12/10/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 123744,
        "overhead_rate": 0.617,
        "task_name": "Regrant",
        "contact_name": "Juanita Flello",
        "contact_phone": "815-611-2061",
        "project_manager": "Jodi Tollady",
        "task_description": "lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque",
        "start_date": "08/04/2018",
        "end_date": "10/01/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 120270,
        "overhead_rate": 0.679,
        "task_name": "Tin",
        "contact_name": "Nikolia Pickthorn",
        "contact_phone": "871-954-1514",
        "project_manager": "Garrard Probbings",
        "task_description": "augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in",
        "start_date": "08/31/2018",
        "end_date": "07/26/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 70235,
        "overhead_rate": 0.561,
        "task_name": "Cookley",
        "contact_name": "Katey Antliff",
        "contact_phone": "440-674-5433",
        "project_manager": "Althea Agate",
        "task_description": "posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut",
        "start_date": "06/13/2018",
        "end_date": "04/08/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 91061,
        "overhead_rate": 0.099,
        "task_name": "Aerified",
        "contact_name": "Deeann Danielsky",
        "contact_phone": "920-770-5228",
        "project_manager": "Mariska Howgill",
        "task_description": "eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum",
        "start_date": "10/12/2017",
        "end_date": "07/02/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 63825,
        "overhead_rate": 0.593,
        "task_name": "Subin",
        "contact_name": "Carmine Lockless",
        "contact_phone": "978-335-2921",
        "project_manager": "Waldo Waddam",
        "task_description": "curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel",
        "start_date": "04/16/2018",
        "end_date": "11/04/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 126109,
        "overhead_rate": 0.759,
        "task_name": "Temp",
        "contact_name": "Ephrem Andino",
        "contact_phone": "836-742-1495",
        "project_manager": "Dehlia Cranstone",
        "task_description": "mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus",
        "start_date": "08/24/2018",
        "end_date": "03/29/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 85565,
        "overhead_rate": 0.245,
        "task_name": "Ventosanzap",
        "contact_name": "Noella Myderscough",
        "contact_phone": "698-868-7655",
        "project_manager": "Robers Cluley",
        "task_description": "fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id",
        "start_date": "09/24/2017",
        "end_date": "12/07/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 28901,
        "overhead_rate": 0.876,
        "task_name": "Lotlux",
        "contact_name": "Bethina Doles",
        "contact_phone": "650-994-6269",
        "project_manager": "Morna Raffin",
        "task_description": "ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem",
        "start_date": "04/16/2018",
        "end_date": "03/27/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 76612,
        "overhead_rate": 0.424,
        "task_name": "Bigtax",
        "contact_name": "Lucky Peggram",
        "contact_phone": "930-237-3191",
        "project_manager": "Dulcine Ianizzi",
        "task_description": "vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque",
        "start_date": "05/02/2018",
        "end_date": "12/05/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 22978,
        "overhead_rate": 0.178,
        "task_name": "Sonsing",
        "contact_name": "Judon Bourges",
        "contact_phone": "996-606-9335",
        "project_manager": "Neale Parcell",
        "task_description": "blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt",
        "start_date": "08/14/2018",
        "end_date": "11/20/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 142209,
        "overhead_rate": 0.987,
        "task_name": "Redhold",
        "contact_name": "Stevy Aslott",
        "contact_phone": "135-354-0491",
        "project_manager": "Klaus Guynemer",
        "task_description": "primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui",
        "start_date": "07/21/2018",
        "end_date": "08/19/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 177359,
        "overhead_rate": 0.879,
        "task_name": "Zamit",
        "contact_name": "Marketa Hurle",
        "contact_phone": "466-619-0691",
        "project_manager": "Fraze Tanslie",
        "task_description": "quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",
        "start_date": "09/03/2018",
        "end_date": "11/09/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 127685,
        "overhead_rate": 0.722,
        "task_name": "Alphazap",
        "contact_name": "Evie Peltz",
        "contact_phone": "288-318-7183",
        "project_manager": "Kerk Gabbott",
        "task_description": "sapien non mi integer ac neque duis bibendum morbi non quam nec",
        "start_date": "08/11/2018",
        "end_date": "07/28/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 94973,
        "overhead_rate": 0.325,
        "task_name": "Cookley",
        "contact_name": "Donnie Arundell",
        "contact_phone": "498-945-5077",
        "project_manager": "Robbert Aguirrezabala",
        "task_description": "sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est",
        "start_date": "02/23/2018",
        "end_date": "01/02/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 197863,
        "overhead_rate": 0.454,
        "task_name": "Sub-Ex",
        "contact_name": "Debi Lavell",
        "contact_phone": "189-671-0681",
        "project_manager": "Claresta Hugonet",
        "task_description": "nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum",
        "start_date": "09/04/2018",
        "end_date": "05/12/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 31824,
        "overhead_rate": 0.034,
        "task_name": "Kanlam",
        "contact_name": "Elfrieda Killcross",
        "contact_phone": "513-935-4563",
        "project_manager": "Kettie Tynewell",
        "task_description": "habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien",
        "start_date": "03/31/2018",
        "end_date": "02/03/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 110658,
        "overhead_rate": 0.357,
        "task_name": "Ronstring",
        "contact_name": "Appolonia Gley",
        "contact_phone": "190-130-8987",
        "project_manager": "Putnem Chisman",
        "task_description": "massa quis augue luctus tincidunt nulla mollis molestie lorem quisque",
        "start_date": "10/02/2017",
        "end_date": "06/24/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 102994,
        "overhead_rate": 0.223,
        "task_name": "Zaam-Dox",
        "contact_name": "Nanon Dorgan",
        "contact_phone": "653-571-7048",
        "project_manager": "Erna Elgram",
        "task_description": "dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et",
        "start_date": "08/12/2018",
        "end_date": "10/28/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 140743,
        "overhead_rate": 0.585,
        "task_name": "Rank",
        "contact_name": "Jock Lodemann",
        "contact_phone": "909-642-3202",
        "project_manager": "Marnie Stampfer",
        "task_description": "nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare",
        "start_date": "11/12/2017",
        "end_date": "01/20/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 173597,
        "overhead_rate": 0.114,
        "task_name": "Zaam-Dox",
        "contact_name": "Shep Hosier",
        "contact_phone": "275-665-5184",
        "project_manager": "Kristopher Radeliffe",
        "task_description": "platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante",
        "start_date": "07/22/2018",
        "end_date": "08/01/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 150418,
        "overhead_rate": 0.871,
        "task_name": "Overhold",
        "contact_name": "Rustin McGowran",
        "contact_phone": "238-699-3298",
        "project_manager": "Shayne Rosenblum",
        "task_description": "nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus",
        "start_date": "07/18/2018",
        "end_date": "09/11/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 16875,
        "overhead_rate": 0.86,
        "task_name": "Cookley",
        "contact_name": "Sterne Chalfont",
        "contact_phone": "403-351-8042",
        "project_manager": "Dana Fautley",
        "task_description": "fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat",
        "start_date": "05/07/2018",
        "end_date": "03/03/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 146982,
        "overhead_rate": 0.975,
        "task_name": "Tempsoft",
        "contact_name": "Lonee Littlejohns",
        "contact_phone": "618-973-9069",
        "project_manager": "Janetta Tamsett",
        "task_description": "tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis",
        "start_date": "06/10/2018",
        "end_date": "08/20/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 143687,
        "overhead_rate": 0.174,
        "task_name": "Fix San",
        "contact_name": "Lewie Skyner",
        "contact_phone": "260-956-2596",
        "project_manager": "Dorothy Mouget",
        "task_description": "consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus",
        "start_date": "07/30/2018",
        "end_date": "01/29/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 189225,
        "overhead_rate": 0.475,
        "task_name": "Stronghold",
        "contact_name": "Grover Varah",
        "contact_phone": "762-225-0337",
        "project_manager": "Jonas Cunio",
        "task_description": "tincidunt lacus at velit vivamus vel nulla eget eros elementum",
        "start_date": "09/24/2017",
        "end_date": "03/25/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 41698,
        "overhead_rate": 0.974,
        "task_name": "Regrant",
        "contact_name": "Emiline Greveson",
        "contact_phone": "136-610-7002",
        "project_manager": "Abram Aitken",
        "task_description": "praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum",
        "start_date": "07/23/2018",
        "end_date": "08/17/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 111719,
        "overhead_rate": 0.988,
        "task_name": "Zontrax",
        "contact_name": "Mitchael Heisham",
        "contact_phone": "606-879-0069",
        "project_manager": "Nichols Lago",
        "task_description": "feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue",
        "start_date": "07/09/2018",
        "end_date": "09/30/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 22774,
        "overhead_rate": 0.091,
        "task_name": "Tin",
        "contact_name": "Tristan Filliskirk",
        "contact_phone": "213-313-0254",
        "project_manager": "Kean Tolle",
        "task_description": "aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce",
        "start_date": "11/26/2017",
        "end_date": "11/02/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 18429,
        "overhead_rate": 0.284,
        "task_name": "Wrapsafe",
        "contact_name": "Merill Cloonan",
        "contact_phone": "206-830-3342",
        "project_manager": "Hana Josephov",
        "task_description": "erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus",
        "start_date": "03/21/2018",
        "end_date": "12/14/2018",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 181863,
        "overhead_rate": 0.87,
        "task_name": "Stim",
        "contact_name": "Davidde Mazin",
        "contact_phone": "809-716-5021",
        "project_manager": "Oberon Kynastone",
        "task_description": "bibendum morbi non quam nec dui luctus rutrum nulla tellus in",
        "start_date": "05/31/2018",
        "end_date": "04/09/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 52372,
        "overhead_rate": 0.23,
        "task_name": "Mat Lam Tam",
        "contact_name": "Silvan Elfes",
        "contact_phone": "638-271-3011",
        "project_manager": "Juieta Shemming",
        "task_description": "fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse",
        "start_date": "10/23/2017",
        "end_date": "09/04/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 15685,
        "overhead_rate": 0.161,
        "task_name": "Flexidy",
        "contact_name": "Gennifer Boldero",
        "contact_phone": "496-693-9317",
        "project_manager": "Nissy Hymer",
        "task_description": "volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc",
        "start_date": "04/15/2018",
        "end_date": "01/12/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 134325,
        "overhead_rate": 0.67,
        "task_name": "Sub-Ex",
        "contact_name": "Gilbertina Fullbrook",
        "contact_phone": "134-867-9808",
        "project_manager": "Pauline Andryushchenko",
        "task_description": "dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi",
        "start_date": "05/03/2018",
        "end_date": "11/28/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 91392,
        "overhead_rate": 0.858,
        "task_name": "Domainer",
        "contact_name": "Roger Mattiuzzi",
        "contact_phone": "175-457-9029",
        "project_manager": "Ula Kingsworth",
        "task_description": "in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non",
        "start_date": "04/07/2018",
        "end_date": "01/23/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 136756,
        "overhead_rate": 0.663,
        "task_name": "Solarbreeze",
        "contact_name": "Kelci Marquiss",
        "contact_phone": "416-650-8424",
        "project_manager": "Garrett Innes",
        "task_description": "in felis donec semper sapien a libero nam dui proin",
        "start_date": "06/19/2018",
        "end_date": "09/17/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 185664,
        "overhead_rate": 0.885,
        "task_name": "Stronghold",
        "contact_name": "Lolita Corre",
        "contact_phone": "377-308-3454",
        "project_manager": "Avrom Turneux",
        "task_description": "habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at",
        "start_date": "08/29/2018",
        "end_date": "01/07/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 67496,
        "overhead_rate": 0.529,
        "task_name": "Keylex",
        "contact_name": "Lilah Flippelli",
        "contact_phone": "772-269-8262",
        "project_manager": "Tomasina Langthorn",
        "task_description": "proin eu mi nulla ac enim in tempor turpis nec euismod",
        "start_date": "03/28/2018",
        "end_date": "05/09/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 77145,
        "overhead_rate": 0.413,
        "task_name": "Flexidy",
        "contact_name": "Byran Sollon",
        "contact_phone": "125-990-4602",
        "project_manager": "Levey Silverlock",
        "task_description": "pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut",
        "start_date": "05/15/2018",
        "end_date": "05/24/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 45039,
        "overhead_rate": 0.908,
        "task_name": "Asoka",
        "contact_name": "Mersey Mepham",
        "contact_phone": "570-866-6243",
        "project_manager": "Bevon Allberry",
        "task_description": "curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam",
        "start_date": "05/23/2018",
        "end_date": "05/07/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 28773,
        "overhead_rate": 0.177,
        "task_name": "Rank",
        "contact_name": "Ware Zupo",
        "contact_phone": "945-141-9224",
        "project_manager": "Roberto Whitney",
        "task_description": "mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue",
        "start_date": "05/24/2018",
        "end_date": "08/25/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 124082,
        "overhead_rate": 0.078,
        "task_name": "Tin",
        "contact_name": "Collin Enriques",
        "contact_phone": "301-246-2607",
        "project_manager": "Romona Eadington",
        "task_description": "nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum",
        "start_date": "12/12/2017",
        "end_date": "11/01/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 50405,
        "overhead_rate": 0.086,
        "task_name": "Ventosanzap",
        "contact_name": "Ezmeralda Riach",
        "contact_phone": "876-811-8242",
        "project_manager": "Goran Wallsworth",
        "task_description": "platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",
        "start_date": "08/17/2018",
        "end_date": "11/15/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 47356,
        "overhead_rate": 0.988,
        "task_name": "Namfix",
        "contact_name": "Jamie Laflin",
        "contact_phone": "437-927-1401",
        "project_manager": "Rutherford Ickeringill",
        "task_description": "luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac",
        "start_date": "08/03/2018",
        "end_date": "12/25/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 35695,
        "overhead_rate": 0.637,
        "task_name": "Treeflex",
        "contact_name": "Nadya Burberow",
        "contact_phone": "401-848-3492",
        "project_manager": "Warde Rumney",
        "task_description": "proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit",
        "start_date": "07/21/2018",
        "end_date": "04/18/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 50451,
        "overhead_rate": 0.222,
        "task_name": "Vagram",
        "contact_name": "Lyell Fawdery",
        "contact_phone": "659-589-8385",
        "project_manager": "Sammy Orred",
        "task_description": "mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus",
        "start_date": "11/06/2017",
        "end_date": "12/26/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 59223,
        "overhead_rate": 0.142,
        "task_name": "Holdlamis",
        "contact_name": "Sigfrid Keppel",
        "contact_phone": "411-512-7283",
        "project_manager": "Sammy Shottin",
        "task_description": "maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum",
        "start_date": "08/02/2018",
        "end_date": "04/05/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 17103,
        "overhead_rate": 0.156,
        "task_name": "Regrant",
        "contact_name": "Blondelle Nelligan",
        "contact_phone": "239-494-9457",
        "project_manager": "Robinson Skehan",
        "task_description": "fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris",
        "start_date": "05/03/2018",
        "end_date": "08/07/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 123978,
        "overhead_rate": 0.489,
        "task_name": "Tin",
        "contact_name": "Brendis Mountcastle",
        "contact_phone": "972-271-8416",
        "project_manager": "Donall Lydall",
        "task_description": "consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna",
        "start_date": "07/13/2018",
        "end_date": "02/25/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 100392,
        "overhead_rate": 0.514,
        "task_name": "Ronstring",
        "contact_name": "Paulita Pauleau",
        "contact_phone": "830-771-7011",
        "project_manager": "Alanna Chalcraft",
        "task_description": "nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque",
        "start_date": "11/01/2017",
        "end_date": "08/01/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 139862,
        "overhead_rate": 0.389,
        "task_name": "Duobam",
        "contact_name": "Creigh Matchell",
        "contact_phone": "155-426-6999",
        "project_manager": "Christye Saffin",
        "task_description": "lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque",
        "start_date": "07/25/2018",
        "end_date": "01/23/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 20936,
        "overhead_rate": 0.844,
        "task_name": "Transcof",
        "contact_name": "Dara Fritz",
        "contact_phone": "930-767-3616",
        "project_manager": "Marlene Cressar",
        "task_description": "morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet",
        "start_date": "07/25/2018",
        "end_date": "12/20/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 174229,
        "overhead_rate": 0.634,
        "task_name": "Flowdesk",
        "contact_name": "Rowney Craise",
        "contact_phone": "254-293-3324",
        "project_manager": "Bev Lawee",
        "task_description": "augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida",
        "start_date": "03/17/2018",
        "end_date": "05/22/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 176659,
        "overhead_rate": 0.732,
        "task_name": "Job",
        "contact_name": "Aaren Pretor",
        "contact_phone": "736-304-1843",
        "project_manager": "Starr Pennino",
        "task_description": "pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare",
        "start_date": "05/16/2018",
        "end_date": "12/27/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 38613,
        "overhead_rate": 0.607,
        "task_name": "Bitwolf",
        "contact_name": "Noel Wanden",
        "contact_phone": "759-860-3256",
        "project_manager": "Samantha Kulvear",
        "task_description": "ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in",
        "start_date": "03/14/2018",
        "end_date": "09/18/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 162239,
        "overhead_rate": 0.715,
        "task_name": "Toughjoyfax",
        "contact_name": "Jemmie Sandy",
        "contact_phone": "415-150-6594",
        "project_manager": "Gwenneth Eskrick",
        "task_description": "vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit",
        "start_date": "08/21/2018",
        "end_date": "03/05/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 182935,
        "overhead_rate": 0.795,
        "task_name": "Voyatouch",
        "contact_name": "Lynnea Breydin",
        "contact_phone": "763-160-3006",
        "project_manager": "Dreddy Quiddihy",
        "task_description": "tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed",
        "start_date": "07/08/2018",
        "end_date": "05/12/2019",
        "billing_structure": "Fixed"
    }, {
        "mou_id": "mou_id",
        "budget": 180728,
        "overhead_rate": 0.798,
        "task_name": "Voyatouch",
        "contact_name": "Beitris Senchenko",
        "contact_phone": "261-851-7432",
        "project_manager": "Janaya Pettipher",
        "task_description": "fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue",
        "start_date": "04/03/2018",
        "end_date": "04/28/2019",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 120779,
        "overhead_rate": 0.786,
        "task_name": "Voyatouch",
        "contact_name": "Hendrika Verbruggen",
        "contact_phone": "598-718-7637",
        "project_manager": "Tracy MacDermott",
        "task_description": "morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo",
        "start_date": "02/08/2018",
        "end_date": "12/29/2018",
        "billing_structure": "Time and Materials"
    }, {
        "mou_id": "mou_id",
        "budget": 155015,
        "overhead_rate": 0.275,
        "task_name": "Subin",
        "contact_name": "Brendin Fortnum",
        "contact_phone": "598-302-6579",
        "project_manager": "Mireille Helks",
        "task_description": "elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus",
        "start_date": "09/18/2018",
        "end_date": "09/30/2018",
        "billing_structure": "Time and Materials"
    }];

    const assignedTasks = taskOrders.map(
        ( task, i ) => assign( {}, task, {
            mou_id: mous[ i % mous.length ].id
        }) );

    await knex( 'task_order' ).insert( assignedTasks );

};
